### PR TITLE
Added exception handling for ExactPrint exceptions

### PR DESCRIPTION
**Pull request by bobbyrauchenberg**

### CODE REVIEW

**Comment by thumphries** [comment]
Hey, thanks for contributing! This works correctly, you've solved the problem.

A couple of small changes before we can merge this:

- The exception handling should probably go into [`parseModule`](https://github.com/thumphries/hgrep/blob/63d59d9e2d57b524a7876d960b143de7e3121251/src/Language/Haskell/HGrep.hs#L39) rather than `main`
- We'll want to turn the exceptions into a [`ParseError`](https://github.com/thumphries/hgrep/blob/63d59d9e2d57b524a7876d960b143de7e3121251/src/Language/Haskell/HGrep/Internal/Data.hs#L37)
    - The easiest way to do this is to turn the `ParseError` newtype into a sum type, with constructors `ExactPrintParseError` and `ExactPrintException`

Let me know if you'd like help with this!

**Comment by bobbyrauchenberg** [comment]
No problem, thanks for the opportunity and your patience, it's much appreciated. 

I think i'm good with the changes you've suggested, however I do have one question. We have this function in `Print.hs`

```haskell
printParseError :: ParseError -> [Char]
printParseError (ParseError (loc, msg)) =
  L.intercalate ": " [
      unsafePpr loc
    , msg
    ]
```

off the back of your suggestion this will need to handle the 2 new data types. 

What should the behaviour be for the `ExactPrintException` case, given it already prints to `stderr`?

I've done something provisionally that just returns an empty `[Char]`:

```haskell
printParseError :: ParseError -> [Char]
printParseError (ExactPrintParseError (loc, msg)) =
  L.intercalate ": " [
      unsafePpr loc
    , msg
    ]
printParseError ExactPrintException = []
```

**Comment by thumphries** [comment]
> What should the behaviour be for the ExactPrintException case, given it already prints to stderr?

There's nothing wrong with adding a message of our own that we control. It's a little redundant right now, but it might not be in future versions of exactprint, and it gives users a string they can search for in the codebase if they're confused by the message.

Maybe something like "Parsing failed unexpectedly with an exception", don't overthink it :)

**Comment by thumphries** [comment]
Also, I've just posted some [contributing guidelines](https://github.com/thumphries/hgrep/blob/master/CONTRIBUTING.md) - as per the last section, feel free to add yourself to `CONTRIBUTORS` as part of this PR!

Edit: and CHANGELOG, if you don't mind

**Comment by thumphries** [comment]
Great stuff, thank you so much! Will merge on green.

**Pull request merged**
