### PR TITLE
Support a wider selection of GHC.

### PR DESCRIPTION
**Pull request by kindaro**
As discussed in #81. 

* I took the liberty to add a bunch of `stack-*.yaml` files and a small build script that runs `stack build --stack-yaml` with them.
* I also re-built the Travis configuration from scratch with `haskell-ci`.

I make no attempt to test on systems other than Linux, as I do not have any available.

### CODE REVIEW

**Comment by kindaro** [comment]
The build is failing for no particular reason. I also had a few of these; you only need to restart the failing entry and it will probably build just fine. It seems Travis has become less reliable recently. [See here][sh] for a successful build of the same commit.

[sh]: https://travis-ci.com/kindaro/hgrep/builds/143276233

**Comment by vaibhavsagar** [comment]
I've restarted that failing entry.

**Comment by kindaro** [comment]
Presto!

**Comment by kindaro** [comment]
@thumphries  Is there something else I can do?

**Pull request merged**
