### PR TITLE
Bump resolver to lts-9.12

### PR DESCRIPTION
**Pull request by vaibhavsagar**

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
Because? :)

**Comment by vaibhavsagar** [comment]
I always bump to the latest resolver as it becomes available. See the commit history and #45.

**Comment by mitchellwrosen** [comment]
Fair enough, carry on then. Just seems unnecessarily laborious to me. A build bot can always be building against the latest & greatest snapshot, no need to keep the project _itself_ constantly shifting LTS targets, IMO.

But, what the hell do I care, I'm just a passer-by. Cheers!

**Comment by thumphries** [comment]
I appreciate the effort nevertheless!

**Pull request merged**
