### PR TITLE
Set up AppVeyor

### PR DESCRIPTION
**Pull request by vaibhavsagar**
View current progress at https://ci.appveyor.com/project/vaibhavsagar/hgrep

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Once I figure out the build matrix and how to install `cabal` I will implement builds across `8.0.1`, `8.0.2`, and `8.2.1`.

**Comment by thumphries** [comment]
Wow, this is some next level stuff. Awesome. Looking forward to merging!

I'm investigating how to coordinate Appveyor and Travis releases into a single GitHub release. It looks like it might not be a thing, since each separate call to GH releases creates a new entry.

What I could do is publish every `master` binary to a private S3 bucket, and make Travis perform the real release on tag push. Sounds OK in the scheme of things.

**Comment by vaibhavsagar** [comment]
I assumed that pushing a tag would group all release files under that tag, is that not the case? We can try after getting it set up but I wasn't planning to get that far in this PR.

**Comment by thumphries** [comment]
Maybe you're right, I'll try the basic thing and see what happens first. My understanding is it will create two releases and/or clobber one another.

**Comment by vaibhavsagar** [comment]
[Progress](https://ci.appveyor.com/project/vaibhavsagar/hgrep/build/1.0.27)! Is it important for you to have `stack` builds working on Windows? If not I can excise `stack` and clean up what I have and it should be ready for review.

**Comment by thumphries** [comment]
> Is it important for you to have stack builds working on Windows? If not I can excise stack and clean up what I have and it should be ready for review.

Not at all! What's important is
- Running the build in at least 1 way
- Running any test suites at least once
- Publishing binaries

The current publish script is here: https://github.com/thumphries/hgrep/blob/master/bin/travis_publish

Does it seem like that is a thing that Appveyor could run on `master`? It depends on a unix shell and `awscli`.

**Comment by vaibhavsagar** [comment]
I think MSYS2 should be able to provide a Unix shell, I will look into it.

**Comment by vaibhavsagar** [comment]
We have `awscli` and bash (see [here](https://ci.appveyor.com/project/vaibhavsagar/hgrep/build/job/oa6amoj52t6o3voq))! I think there needs to be an `appveyor-shim.sh` or something that translates between Windows-style `%ENVIRONMENT_VARIABLE%`s and the Linux `$VARIABLE`s your publish script is expecting.

**Comment by thumphries** [comment]
Sweet, that's awesome! I could write a new script for Windows, as long as awscli is available we are good! Is it time for me to get appveyor going on this repo?

**Comment by vaibhavsagar** [comment]
I think we could repurpose the existing script to handle Windows binaries ending with `.exe` and do something along the lines of having an `appveyor.sh` that looked like

```bash
export GITHUB_OAUTH_TOKEN="$1"
export PUBLISH_BUCKET="$2"
export PUBLISH_KEY="$3"
export PUBLISH_REGION="$4"
export PUBLISH_SECRET="$5"
bin/travis_publish
```
and then calling it from `appveyor.yml` like

```yaml
deploy_script:
  - bash bin/appveyor.sh %GITHUB_OAUTH_TOKEN% %PUBLISH_BUCKET% %PUBLISH_KEY% %PUBLISH_REGION% %PUBLISH_SECRET%
```
assuming those environment variables are defined in AppVeyor.

Let me know if you want any of those changes to be part of this PR or if they can be separate.

**Comment by thumphries** [comment]
> Let me know if you want any of those changes to be part of this PR or if they can be separate.

Separate is good! This looked like some really fiddly work, I'm going to reuse this config over and over again, thank you so much for rigging it up. I'll configure AppVeyor tonight and see how it goes.

**Comment by thumphries** [comment]
> tonight

> 3 days ago

Whoops.

Can't figure out how to trigger an AppVeyor build on an arbitrary branch, so I'll just merge as-is and go from there.

**Pull request merged**
